# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        additional_dependencies: ['click<8.1']
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.5b1]
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear              # finds likely bugs and design problems
          - flake8-comprehensions       # helps you write better comprehensions
          - darglint                    # checks docstring format
          - flake8-debugger             # ipdb/pdb statement checker
          - flake8-eradicate            # finds commented code
          - flake8-pytest-style         # checks style issues with pytest tests
          - flake8_isort                # checks imports are correctly sorted
          - pep8-naming                 # checks PEP-8 naming conventions
          - pycodestyle                 # general style guide checker
          - flake8-docstrings           # punctuation docstring checks
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: 'src/.*'
      - id: isort
        files: 'tests/.*'
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

exclude: alembic
