version: "3.8"

x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  users_crud:
    image: users_crud
    build:
      context: ..
      dockerfile: docker/Dockerfile
    logging: *logging
    init: true
    ports:
      - 3000:3000
    tty: true
    env_file:
      - ../config/api.env
      - ../config/db.env
    environment:
        - ENVIRONMENT=production
    depends_on:
      - db

  db:
    image: postgres:12
    # volumes:
    # - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    env_file:
      - ../config/db.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.3
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8001:80
    restart: unless-stopped
    depends_on:
      - db
