version: "3.8"

x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  users-api:
    image: users_api:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    logging: *logging
    init: true
    ports:
      - 3000:3000
    tty: true
    command: sleep infinity
    volumes:
      - ../src/users_api:/app/users_api
      - ../tests:/app/tests
      - ../alembic:/app/alembic
      # Mount poetry files to edit them from inside the container
      - ../pyproject.toml:/app/pyproject.toml
      - ../poetry.lock:/app/poetry.lock
    env_file:
      - ../config/api.env
      - ../config/db.env
#    environment:
#        - ENVIRONMENT=production
    depends_on:
      - db

  db:
    image: postgres:12
    # volumes:
    # - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    env_file:
      - ../config/db.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8001:80
    restart: unless-stopped
    depends_on:
      - db
